import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Treatment } from "@/data/treatments";

interface DownloadGuideProps {
  disease: string;
  confidence: number;
  treatment: Treatment;
  weatherAdvice?: string;
}

export function DownloadGuide({ disease, confidence, treatment, weatherAdvice }: DownloadGuideProps) {
  const generateGuideText = () => {
    const timestamp = new Date().toLocaleString();
    
    return `
═══════════════════════════════════════════
    CROPGPT - OFFLINE TREATMENT GUIDE
═══════════════════════════════════════════

Generated: ${timestamp}

───────────────────────────────────────────
DIAGNOSIS
───────────────────────────────────────────

Disease Detected: ${treatment.disease}
Confidence Level: ${confidence.toFixed(1)}%
Severity: ${treatment.severity.toUpperCase()}

───────────────────────────────────────────
TREATMENT INSTRUCTIONS
───────────────────────────────────────────

${treatment.treatment}

───────────────────────────────────────────
PREVENTION TIPS
───────────────────────────────────────────

${treatment.prevention}

${weatherAdvice ? `───────────────────────────────────────────
WEATHER-BASED ADVICE
───────────────────────────────────────────

${weatherAdvice}
` : ''}
───────────────────────────────────────────
IMPORTANT REMINDERS
───────────────────────────────────────────

• Always wear protective equipment when applying chemicals
• Follow recommended dosage carefully
• Avoid spraying during windy conditions
• Keep records of treatments applied
• Consult local agricultural extension for severe cases

───────────────────────────────────────────

Generated by CropGPT - AI Farmer's Companion
For more information, visit your local agricultural office

═══════════════════════════════════════════
`;
  };

  const handleDownload = () => {
    const text = generateGuideText();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CropGPT_Treatment_Guide_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Button
      onClick={handleDownload}
      size="lg"
      className="w-full"
      variant="secondary"
    >
      <Download className="w-5 h-5 mr-2" />
      Download Offline Treatment Guide
    </Button>
  );
}
